const quotes = [
    "“The only way to do great work is to love what you do.”\n- Steve Jobs\n\n",
    "“The future belongs to those who believe in the beauty of their dreams.”\n- Eleanor Roosevelt\n\n",
    "“Success is not final, failure is not fatal: It is the courage to continue that counts.”\n- Winston Churchill\n\n",
    "“The only person you should try to be better than is the person you were yesterday.”\n- Unknown\n\n",
    "“The best revenge is massive success.”\n- Frank Sinatra\n\n",
    "“Your time is limited, don't waste it living someone else's life.”\n- Steve Jobs\n\n",
    "“Believe you can and you're halfway there.”\n- Theodore Roosevelt\n\n",
    "“In the middle of every difficulty lies opportunity.”\n- Albert Einstein\n\n",
    "“Don't watch the clock; do what it does. Keep going.”\n- Sam Levenson\n\n",
    "“The biggest risk is not taking any risk.”\n- Mark Zuckerberg\n\n",
    "“The only limit to our realization of tomorrow will be our doubts of today.”\n- Franklin D. Roosevelt\n\n",
    "“Success usually comes to those who are too busy to be looking for it.”\n- Henry David Thoreau\n\n",
    "“Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.”\n- Steve Jobs\n\n",
    "“The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.”\n- Jordan Belfort\n\n",
    "“Believe in yourself, take on your challenges, dig deep within yourself to conquer fears. Never let anyone bring you down. You got this.”\n- Chantal Sutherland\n\n",
    "“The best way to predict the future is to create it.”\n- Peter Drucker\n\n",
    "“I can't change the direction of the wind, but I can adjust my sails to always reach my destination.”\n- Jimmy Dean\n\n",
    "“The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will.”\n- Vince Lombardi\n\n",
    "“Life is 10% what happens to us and 90% how we react to it.”\n- Charles R. Swindoll\n\n",
    "“The harder I work, the luckier I get.”\n- Samuel Goldwyn\n\n",
    "“It does not matter how slowly you go as long as you do not stop.”\n- Confucius\n\n",
    "“The greatest glory in living lies not in never falling, but in rising every time we fall.”\n- Nelson Mandela\n\n",
    "“The only way to do great work is to love what you do.”\n- Steve Jobs\n\n",
    "“Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.”\n- Roy T. Bennett\n\n",
    "“Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.”\n- Albert Schweitzer\n\n",
    "“You miss 100% of the shots you don't take.”\n- Wayne Gretzky\n\n",
    "“The only person you are destined to become is the person you decide to be.”\n- Ralph Waldo Emerson\n\n",
    "“The best revenge is massive success.”\n- Frank Sinatra\n\n",
    "“Believe you can and you're halfway there.”\n- Theodore Roosevelt\n\n",
    "“The future belongs to those who believe in the beauty of their dreams.”\n- Eleanor Roosevelt\n\n",
    "“You are never too old to set another goal or to dream a new dream.”\n- C.S. Lewis\n\n",
    "“Don't be afraid to give up the good to go for the great.”\n- John D. Rockefeller\n\n",
    "“The only way to achieve the impossible is to believe it is possible.”\n- Charles Kingsleigh\n\n",
    "“Success is not in what you have, but who you are.”\n- Bo Bennett\n\n",
    "“The best time to plant a tree was 20 years ago. The second best time is now.”\n- Chinese Proverb\n\n",
    "“The only person you should try to be better than is the person you were yesterday.”\n- Unknown\n\n",
    "“Happiness is not something ready-made. It comes from your own actions.”\n- Dalai Lama\n\n",
    "“Your time is limited, don't waste it living someone else's life.”\n- Steve Jobs\n\n",
    "“Believe you can and you're halfway there.”\n- Theodore Roosevelt\n\n",
    "“In the middle of every difficulty lies opportunity.”\n- Albert Einstein\n\n",
    "“Don't watch the clock; do what it does. Keep going.”\n- Sam Levenson\n\n",
    "“The biggest risk is not taking any risk.”\n- Mark Zuckerberg\n\n",
    "“The only limit to our realization of tomorrow will be our doubts of today.”\n- Franklin D. Roosevelt\n\n",
    "“Success usually comes to those who are too busy to be looking for it.”\n- Henry David Thoreau\n\n",
    "“Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.”\n- Steve Jobs\n\n",
    "“The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.”\n- Jordan Belfort\n\n",
    "“Believe in yourself, take on your challenges, dig deep within yourself to conquer fears. Never let anyone bring you down. You got this.”\n- Chantal Sutherland\n\n",
    "“The best way to predict the future is to create it.”\n- Peter Drucker\n\n",
    "“I can't change the direction of the wind, but I can adjust my sails to always reach my destination.”\n- Jimmy Dean\n\n",
    "“The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will.”\n- Vince Lombardi\n\n",
    "“Life is 10% what happens to us and 90% how we react to it.”\n- Charles R. Swindoll\n\n",
    "“The harder I work, the luckier I get.”\n- Samuel Goldwyn\n\n",
    "“It does not matter how slowly you go as long as you do not stop.”\n- Confucius\n\n",
    "“The greatest glory in living lies not in never falling, but in rising every time we fall.”\n- Nelson Mandela\n\n",
    "“The only way to do great work is to love what you do.”\n- Steve Jobs\n\n",
    "“Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.”\n- Roy T. Bennett\n\n",
    "“Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.”\n- Albert Schweitzer\n\n",
    "“You miss 100% of the shots you don't take.”\n- Wayne Gretzky\n\n",
    "“The only person you are destined to become is the person you decide to be.”\n- Ralph Waldo Emerson\n\n",
    "“The best revenge is massive success.”\n- Frank Sinatra\n\n",
    "“Believe you can and you're halfway there.”\n- Theodore Roosevelt\n\n",
    "“The future belongs to those who believe in the beauty of their dreams.”\n- Eleanor Roosevelt\n\n",
    "“You are never too old to set another goal or to dream a new dream.”\n- C.S. Lewis\n\n",
    "“It's not about how hard you hit. It's about how hard you can get hit and keep moving forward.”\n- Rocky Balboa\n\n",
    "“Success is not the absence of failure; it's the persistence through failure.”\n- Aisha Tyler\n\n",
    "“The only person you are destined to become is the person you decide to be.”\n- Ralph Waldo Emerson\n\n",
    "“Life is either a daring adventure or nothing at all.”\n- Helen Keller\n\n",
    "“The purpose of our lives is to be happy.”\n- Dalai Lama\n\n",
    "“Don't let yesterday take up too much of today.”\n- Will Rogers\n\n",
    "“The only limit to our realization of tomorrow will be our doubts of today.”\n- Franklin D. Roosevelt\n\n",
    "“Challenges are what make life interesting and overcoming them is what makes life meaningful.”\n- Joshua J. Marine\n\n",
    "“The greatest pleasure in life is doing what people say you cannot do.”\n- Walter Bagehot\n\n",
    "“You are the average of the five people you spend the most time with.”\n- Jim Rohn\n\n",
    "“The best revenge is massive success.”\n- Frank Sinatra\n\n",
    "“If you want to achieve greatness, stop asking for permission.”\n- Anonymous\n\n",
    "“Your time is limited, don't waste it living someone else's life.”\n- Steve Jobs\n\n",
    "“Believe you can and you're halfway there.”\n- Theodore Roosevelt\n\n",
    "“In the middle of every difficulty lies opportunity.”\n- Albert Einstein\n\n",
    "“Success usually comes to those who are too busy to be looking for it.”\n- Henry David Thoreau\n\n",
    "“The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.”\n- Jordan Belfort\n\n",
    "“Believe in yourself, take on your challenges, dig deep within yourself to conquer fears. Never let anyone bring you down. You got this.”\n- Chantal Sutherland\n\n",
    "“The best way to predict the future is to create it.”\n- Peter Drucker\n\n",
    "“I can't change the direction of the wind, but I can adjust my sails to always reach my destination.”\n- Jimmy Dean\n\n",
    "“The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will.”\n- Vince Lombardi\n\n",
    "“Life is 10% what happens to us and 90% how we react to it.”\n- Charles R. Swindoll\n\n",
    "“The harder I work, the luckier I get.”\n- Samuel Goldwyn\n\n",
    "“It does not matter how slowly you go as long as you do not stop.”\n- Confucius\n\n",
    "“The greatest glory in living lies not in never falling, but in rising every time we fall.”\n- Nelson Mandela\n\n",
    "“The only way to do great work is to love what you do.”\n- Steve Jobs\n\n",
    "“Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.”\n- Roy T. Bennett\n\n",
    "“Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.”\n- Albert Schweitzer\n\n",
    "“You miss 100% of the shots you don't take.”\n- Wayne Gretzky\n\n",
    "“The only person you are destined to become is the person you decide to be.”\n- Ralph Waldo Emerson\n\n",
    "“The future belongs to those who believe in the beauty of their dreams.”\n- Eleanor Roosevelt\n\n",
    "“You are never too old to set another goal or to dream a new dream.”\n- C.S. Lewis\n\n",
    "“It's not about how hard you hit. It's about how hard you can get hit and keep moving forward.”\n- Rocky Balboa\n\n",
    "“Success is not the absence of failure; it's the persistence through failure.”\n- Aisha Tyler\n\n",
    "“Life is either a daring adventure or nothing at all.”\n- Helen Keller\n\n",
    "“The purpose of our lives is to be happy.”\n- Dalai Lama\n\n",
];

export default quotes;
